name: sync_socket
<<<<<<< HEAD
version: 0.0.6
author: Marc Fisher <fisherii@google.com>
description: Synchronous Socket and HTTP Client.
environment:
  sdk: '>=1.4.0 <2.0.0'
=======
version: 0.0.8
author: Marc Fisher <fisherii@google.com>
description: Synchronous Socket and HTTP Client.
environment:
  sdk: '>=1.3.0 <2.0.0'
>>>>>>> 588276d7d865c1c5c18fe637b1fb79bb9854ae4c
dev_dependencies:
  unittest: '>=0.9.0 <0.10.0'
