name: sync_socket
version: 1.0.0
author: Marc Fisher <fisherii@google.com>
description: Synchronous Socket and HTTP Client.
environment:
  sdk: '>=1.7.2 <2.0.0'
dev_dependencies:
  unittest: '>=0.11.0+5 <0.12.0'
