name: sync_socket
version: 1.0.2+1
author:
  - Marc Fisher II <fisherii@google.com>
description: Synchronous Socket and HTTP Client.
homepage: https://github.com/google/dart-sync-socket
environment:
  sdk: '>=1.9.0 <2.0.0'
dev_dependencies:
  test: '^0.12.0'
