name: sync_socket
version: 0.0.6
author: Marc Fisher <fisherii@google.com>
description: Synchronous Socket and HTTP Client.
environment:
  sdk: '>=1.4.0 <2.0.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.10.0'
