name: sync_socket
version: 1.0.1
author: Marc Fisher <fisherii@google.com>
description: Synchronous Socket and HTTP Client.
environment:
  sdk: '>=1.8.0 <2.0.0'
dev_dependencies:
  unittest: '^0.11.5+4'
